const partidos = [
  {id:1, grupo:"Grupo A", equipo1:"México", equipo2:"Sudáfrica"},
  {id:2, grupo:"Grupo A", equipo1:"Corea del Sur", equipo2:"Rep. Checa"},
  {id:3, grupo:"Grupo A", equipo1:"México", equipo2:"Corea del Sur"},
  {id:4, grupo:"Grupo A", equipo1:"Sudáfrica", equipo2:"Rep. Checa"},
  {id:5, grupo:"Grupo A", equipo1:"Sudáfrica", equipo2:"Corea del Sur"},
  {id:6, grupo:"Grupo A", equipo1:"Rep. Checa", equipo2:"México"},

  {id:7, grupo:"Grupo B", equipo1:"Canadá", equipo2:"Bosnia y Herzegovina"},
  {id:8, grupo:"Grupo B", equipo1:"Qatar", equipo2:"Suiza"},
  {id:9, grupo:"Grupo B", equipo1:"Canadá", equipo2:"Qatar"},
  {id:10, grupo:"Grupo B", equipo1:"Bosnia y Herzegovina", equipo2:"Suiza"},
  {id:11, grupo:"Grupo B", equipo1:"Bosnia y Herzegovina", equipo2:"Qatar"},
  {id:12, grupo:"Grupo B", equipo1:"Suiza", equipo2:"Canadá"},

  {id:13, grupo:"Grupo C", equipo1:"Brasil", equipo2:"Marruecos"},
  {id:14, grupo:"Grupo C", equipo1:"Haití", equipo2:"Escocia"},
  {id:15, grupo:"Grupo C", equipo1:"Brasil", equipo2:"Haití"},
  {id:16, grupo:"Grupo C", equipo1:"Marruecos", equipo2:"Escocia"},
  {id:17, grupo:"Grupo C", equipo1:"Marruecos", equipo2:"Haití"},
  {id:18, grupo:"Grupo C", equipo1:"Escocia", equipo2:"Brasil"},

  {id:19, grupo:"Grupo D", equipo1:"Estados Unidos", equipo2:"Paraguay"},
  {id:20, grupo:"Grupo D", equipo1:"Australia", equipo2:"Turquía"},
  {id:21, grupo:"Grupo D", equipo1:"Estados Unidos", equipo2:"Australia"},
  {id:22, grupo:"Grupo D", equipo1:"Paraguay", equipo2:"Turquía"},
  {id:23, grupo:"Grupo D", equipo1:"Paraguay", equipo2:"Australia"},
  {id:24, grupo:"Grupo D", equipo1:"Turquía", equipo2:"Estados Unidos"},

  {id:25, grupo:"Grupo E", equipo1:"Alemania", equipo2:"Curazao"},
  {id:26, grupo:"Grupo E", equipo1:"Costa de Marfil", equipo2:"Ecuador"},
  {id:27, grupo:"Grupo E", equipo1:"Alemania", equipo2:"Costa de Marfil"},
  {id:28, grupo:"Grupo E", equipo1:"Curazao", equipo2:"Ecuador"},
  {id:29, grupo:"Grupo E", equipo1:"Curazao", equipo2:"Costa de Marfil"},
  {id:30, grupo:"Grupo E", equipo1:"Ecuador", equipo2:"Alemania"},

  {id:31, grupo:"Grupo F", equipo1:"Países Bajos", equipo2:"Japón"},
  {id:32, grupo:"Grupo F", equipo1:"Suecia", equipo2:"Túnez"},
  {id:33, grupo:"Grupo F", equipo1:"Países Bajos", equipo2:"Suecia"},
  {id:34, grupo:"Grupo F", equipo1:"Japón", equipo2:"Túnez"},
  {id:35, grupo:"Grupo F", equipo1:"Japón", equipo2:"Suecia"},
  {id:36, grupo:"Grupo F", equipo1:"Túnez", equipo2:"Países Bajos"},

  {id:37, grupo:"Grupo G", equipo1:"Bélgica", equipo2:"Egipto"},
  {id:38, grupo:"Grupo G", equipo1:"Irán", equipo2:"Nueva Zelanda"},
  {id:39, grupo:"Grupo G", equipo1:"Bélgica", equipo2:"Irán"},
  {id:40, grupo:"Grupo G", equipo1:"Egipto", equipo2:"Nueva Zelanda"},
  {id:41, grupo:"Grupo G", equipo1:"Egipto", equipo2:"Irán"},
  {id:42, grupo:"Grupo G", equipo1:"Nueva Zelanda", equipo2:"Bélgica"},

  {id:43, grupo:"Grupo H", equipo1:"España", equipo2:"Cabo Verde"},
  {id:44, grupo:"Grupo H", equipo1:"Arabia Saudita", equipo2:"Uruguay"},
  {id:45, grupo:"Grupo H", equipo1:"España", equipo2:"Arabia Saudita"},
  {id:46, grupo:"Grupo H", equipo1:"Cabo Verde", equipo2:"Uruguay"},
  {id:47, grupo:"Grupo H", equipo1:"Cabo Verde", equipo2:"Arabia Saudita"},
  {id:48, grupo:"Grupo H", equipo1:"Uruguay", equipo2:"España"},

  {id:49, grupo:"Grupo I", equipo1:"Francia", equipo2:"Senegal"},
  {id:50, grupo:"Grupo I", equipo1:"Irak", equipo2:"Noruega"},
  {id:51, grupo:"Grupo I", equipo1:"Francia", equipo2:"Irak"},
  {id:52, grupo:"Grupo I", equipo1:"Senegal", equipo2:"Noruega"},
  {id:53, grupo:"Grupo I", equipo1:"Senegal", equipo2:"Irak"},
  {id:54, grupo:"Grupo I", equipo1:"Noruega", equipo2:"Francia"},

  {id:55, grupo:"Grupo J", equipo1:"Argentina", equipo2:"Argelia"},
  {id:56, grupo:"Grupo J", equipo1:"Austria", equipo2:"Jordania"},
  {id:57, grupo:"Grupo J", equipo1:"Argentina", equipo2:"Austria"},
  {id:58, grupo:"Grupo J", equipo1:"Argelia", equipo2:"Jordania"},
  {id:59, grupo:"Grupo J", equipo1:"Argelia", equipo2:"Austria"},
  {id:60, grupo:"Grupo J", equipo1:"Jordania", equipo2:"Argentina"},

  {id:61, grupo:"Grupo K", equipo1:"Portugal", equipo2:"República Democrática del Congo"},
  {id:62, grupo:"Grupo K", equipo1:"Uzbekistán", equipo2:"Colombia"},
  {id:63, grupo:"Grupo K", equipo1:"Portugal", equipo2:"Uzbekistán"},
  {id:64, grupo:"Grupo K", equipo1:"República Democrática del Congo", equipo2:"Colombia"},
  {id:65, grupo:"Grupo K", equipo1:"República Democrática del Congo", equipo2:"Uzbekistán"},
  {id:66, grupo:"Grupo K", equipo1:"Colombia", equipo2:"Portugal"},

  {id:67, grupo:"Grupo L", equipo1:"Inglaterra", equipo2:"Croacia"},
  {id:68, grupo:"Grupo L", equipo1:"Ghana", equipo2:"Panamá"},
  {id:69, grupo:"Grupo L", equipo1:"Inglaterra", equipo2:"Ghana"},
  {id:70, grupo:"Grupo L", equipo1:"Croacia", equipo2:"Panamá"},
  {id:71, grupo:"Grupo L", equipo1:"Croacia", equipo2:"Ghana"},
  {id:72, grupo:"Grupo L", equipo1:"Panamá", equipo2:"Inglaterra"}
];